<?php

declare(strict_types=1);

namespace Moon\Core;

use Moon\Core\Collection\CliPipelineArrayCollection;
use Moon\Core\Collection\CliPipelineCollectionInterface;
use Moon\Core\Pipeline\CliPipeline;

class Cli
{
    /**
     * @var CliPipelineArrayCollection $cliPipelinesCollection
     */
    private $cliPipelinesCollection;

    /**
     * @var string
     */
    private $prefix;
    /**
     * @var array|callable|CliPipeline|null|string
     */
    private $cliStages;

    /**
     * Cli constructor.
     * @param string $prefix
     * @param callable|string|CliPipeline|array $cliStages
     */
    public function __construct(string $prefix = '', $cliStages = null)
    {
        $this->prefix = $prefix;
        $this->cliStages = $cliStages;
        $this->cliPipelinesCollection = new CliPipelineArrayCollection();
    }

    /**
     * Add a command to be handled by the application
     *
     * @param string $pattern
     * @param callable|string|CliPipeline|array $stages
     *
     * @return void
     */
    public function command(string $pattern, $stages): void
    {
        $pipeline = new CliPipeline($this->prefix . $pattern, $this->cliStages);
        $pipeline->pipe($stages);
        $this->cliPipelinesCollection->add($pipeline);
    }

    /**
     * Return all pipelines generated by the command
     *
     * @return CliPipelineCollectionInterface
     */
    public function pipelines(): CliPipelineCollectionInterface
    {
        return $this->cliPipelinesCollection;
    }
}