<?php

declare(strict_types=1);

namespace Moon\Core;

use Moon\Core\Collection\CliPipelineArrayCollection;
use Moon\Core\Collection\CliPipelineCollectionInterface;
use Moon\Core\Pipeline\CliPipeline;

class Cli
{
    /**
     * @var CliPipeline[] $cliPipelines
     */
    protected $cliPipelines = [];

    /**
     * Add a command to be handled by the application
     *
     * @param string $pattern
     * @param array $stages
     *
     * @return void
     */
    public function command(string $pattern, array $stages): void
    {
        $cliPipeline = new CliPipeline($pattern);
        $cliPipeline->pipe($stages);
        $this->cliPipelines[] = $cliPipeline;
    }

    /**
     * Return all pipelines generated by the command
     *
     * @return CliPipelineCollectionInterface
     */
    public function pipelines(): CliPipelineCollectionInterface
    {
        return new CliPipelineArrayCollection($this->cliPipelines);
    }
}