<?php

declare(strict_types=1);

namespace Moon\Core;

use Moon\Core\Collection\PipelineArrayCollection;
use Moon\Core\Collection\PipelineCollectionInterface;
use Moon\Core\Pipeline\HttpPipeline;

class Router
{
    /**
     * @var PipelineArrayCollection $pipelineCollection
     */
    private $pipelineCollection;

    /**
     * @var string $prefix
     */
    private $prefix;

    /**
     * @var callable|string|HttpPipeline|array $routerStages
     */
    private $routerStages;

    /**
     * Router constructor.
     *
     * @param string $prefix
     * @param callable|string|HttpPipeline|array $routerStages
     */
    public function __construct(string $prefix = '', $routerStages = null)
    {
        $this->prefix = $prefix;
        $this->pipelineCollection = new PipelineArrayCollection();
        $this->routerStages = $routerStages;
    }

    /**
     * Add a 'GET' route to be handled by the application
     *
     * @param string $pattern
     * @param callable|string|HttpPipeline|array $stages $stages
     *
     * @return void
     */
    public function get(string $pattern, $stages): void
    {
        $pipeline = new HttpPipeline('GET', $this->prefix . $pattern, $this->routerStages);
        $pipeline->pipe($stages);
        $this->pipelineCollection->add($pipeline);

    }

    /**
     * Add a 'POST' route to be handled by the application
     *
     * @param string $pattern
     * @param callable|string|HttpPipeline|array $stages $stages
     *
     * @return void
     */
    public function post(string $pattern, $stages): void
    {
        $pipeline = new HttpPipeline('POST', $this->prefix . $pattern, $this->routerStages);
        $pipeline->pipe($stages);
        $this->pipelineCollection->add($pipeline);
    }

    /**
     * Add a 'PUT' route to be handled by the application
     *
     * @param string $pattern
     * @param callable|string|HttpPipeline|array $stages $stages
     *
     * @return void
     */
    public function put(string $pattern, $stages): void
    {
        $pipeline = new HttpPipeline('PUT', $this->prefix . $pattern, $this->routerStages);
        $pipeline->pipe($stages);
        $this->pipelineCollection->add($pipeline);
    }

    /**
     * Add a 'PATCH' route to be handled by the application
     *
     * @param string $pattern
     * @param callable|string|HttpPipeline|array $stages $stages
     *
     * @return void
     */
    public function patch(string $pattern, $stages): void
    {
        $pipeline = new HttpPipeline('PATCH', $this->prefix . $pattern, $this->routerStages);
        $pipeline->pipe($stages);
        $this->pipelineCollection->add($pipeline);
    }

    /**
     * Add a 'DELETE' route to be handled by the application
     *
     * @param string $pattern
     * @param callable|string|HttpPipeline|array $stages $stages
     *
     * @return void
     */
    public function delete(string $pattern, $stages): void
    {
        $pipeline = new HttpPipeline('DELETE', $this->prefix . $pattern, $this->routerStages);
        $pipeline->pipe($stages);
        $this->pipelineCollection->add($pipeline);
    }

    /**
     * Add a 'OPTIONS' route to be handled by the application
     *
     * @param string $pattern
     * @param callable|string|HttpPipeline|array $stages $stages
     *
     * @return void
     */
    public function options(string $pattern, $stages): void
    {
        $pipeline = new HttpPipeline('OPTIONS', $this->prefix . $pattern, $this->routerStages);
        $pipeline->pipe($stages);
        $this->pipelineCollection->add($pipeline);
    }

    /**
     * Add a 'HEAD' route to be handled by the application
     *
     * @param string $pattern
     * @param callable|string|HttpPipeline|array $stages $stages
     *
     * @return void
     */
    public function head(string $pattern, $stages): void
    {
        $pipeline = new HttpPipeline('HEAD', $this->prefix . $pattern, $this->routerStages);
        $pipeline->pipe($stages);
        $this->pipelineCollection->add($pipeline);
    }

    /**
     * Add multiple verb to a pattern and stages
     *
     * @param string $pattern
     * @param array $verbs
     * @param callable|string|HttpPipeline|array $stages $stages
     *
     * @return void
     *
     * @throws \Moon\Core\Exception\InvalidArgumentException
     */
    public function map(string $pattern, array $verbs, $stages): void
    {
        $pipeline = new HttpPipeline($verbs, $this->prefix . $pattern, $this->routerStages);
        $pipeline->pipe($stages);
        $this->pipelineCollection->add($pipeline);
    }

    /**
     * Return all pipelines generated by the router
     *
     * @return PipelineCollectionInterface
     */
    public function pipelines(): PipelineCollectionInterface
    {
        return $this->pipelineCollection;
    }
}